# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "E:/ECE385/lab6_2.xpr/lab6_2/lab6_2.runs/synth_1/.Xil/Vivado-11704-DESKTOP-02DFB66/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7s50csga324-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    e:/ECE385/lab6_2.xpr/lab6_2/lab6_2.gen/sources_1/bd/mb_block/ipshared/ec67/hdl
    e:/ECE385/lab6_2.xpr/lab6_2/lab6_2.gen/sources_1/bd/mb_block/ipshared/7698
    e:/ECE385/lab6_2.xpr/lab6_2/lab6_2.gen/sources_1/ip/clk_wiz_0
    e:/ECE385/lab6_2.xpr/lab6_2/lab6_2.gen/sources_1/bd/mb_block/ip/mb_block_axi_quad_spi_0_0/netlist
  } {
      E:/Vivado/2022.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      E:/Vivado/2022.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv
      E:/Vivado/2022.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -sv -include {
    e:/ECE385/lab6_2.xpr/lab6_2/lab6_2.gen/sources_1/bd/mb_block/ipshared/ec67/hdl
    e:/ECE385/lab6_2.xpr/lab6_2/lab6_2.gen/sources_1/bd/mb_block/ipshared/7698
    e:/ECE385/lab6_2.xpr/lab6_2/lab6_2.gen/sources_1/ip/clk_wiz_0
    e:/ECE385/lab6_2.xpr/lab6_2/lab6_2.gen/sources_1/bd/mb_block/ip/mb_block_axi_quad_spi_0_0/netlist
  } {
      E:/ECE385/lab6_2.xpr/lab6_2/lab6_2.srcs/sources_1/imports/design_source/Color_Mapper.sv
      E:/ECE385/lab6_2.xpr/lab6_2/lab6_2.srcs/sources_1/imports/design_source/VGA_controller.sv
      E:/ECE385/lab6_2.xpr/lab6_2/lab6_2.srcs/sources_1/imports/design_source/ball.sv
      E:/ECE385/lab6_2.xpr/lab6_2/lab6_2.srcs/sources_1/new/block.sv
      E:/ECE385/lab6_2.xpr/lab6_2/lab6_2.srcs/sources_1/imports/design_source/hex.sv
      E:/ECE385/lab6_2.xpr/lab6_2/lab6_2.srcs/sources_1/new/paddle.sv
      E:/ECE385/lab6_2.xpr/lab6_2/lab6_2.srcs/sources_1/imports/design_source/mb_usb_hdmi_top.sv
    }
      rt::read_verilog -include {
    e:/ECE385/lab6_2.xpr/lab6_2/lab6_2.gen/sources_1/bd/mb_block/ipshared/ec67/hdl
    e:/ECE385/lab6_2.xpr/lab6_2/lab6_2.gen/sources_1/bd/mb_block/ipshared/7698
    e:/ECE385/lab6_2.xpr/lab6_2/lab6_2.gen/sources_1/ip/clk_wiz_0
    e:/ECE385/lab6_2.xpr/lab6_2/lab6_2.gen/sources_1/bd/mb_block/ip/mb_block_axi_quad_spi_0_0/netlist
  } {
      E:/ECE385/lab6_2.xpr/lab6_2/lab6_2.runs/synth_1/.Xil/Vivado-11704-DESKTOP-02DFB66/realtime/mb_block_microblaze_0_0_stub.v
      E:/ECE385/lab6_2.xpr/lab6_2/lab6_2.runs/synth_1/.Xil/Vivado-11704-DESKTOP-02DFB66/realtime/mb_block_dlmb_v10_0_stub.v
      E:/ECE385/lab6_2.xpr/lab6_2/lab6_2.runs/synth_1/.Xil/Vivado-11704-DESKTOP-02DFB66/realtime/mb_block_ilmb_v10_0_stub.v
      E:/ECE385/lab6_2.xpr/lab6_2/lab6_2.runs/synth_1/.Xil/Vivado-11704-DESKTOP-02DFB66/realtime/mb_block_dlmb_bram_if_cntlr_0_stub.v
      E:/ECE385/lab6_2.xpr/lab6_2/lab6_2.runs/synth_1/.Xil/Vivado-11704-DESKTOP-02DFB66/realtime/mb_block_ilmb_bram_if_cntlr_0_stub.v
      E:/ECE385/lab6_2.xpr/lab6_2/lab6_2.runs/synth_1/.Xil/Vivado-11704-DESKTOP-02DFB66/realtime/mb_block_lmb_bram_0_stub.v
      E:/ECE385/lab6_2.xpr/lab6_2/lab6_2.runs/synth_1/.Xil/Vivado-11704-DESKTOP-02DFB66/realtime/mb_block_xbar_0_stub.v
      E:/ECE385/lab6_2.xpr/lab6_2/lab6_2.runs/synth_1/.Xil/Vivado-11704-DESKTOP-02DFB66/realtime/mb_block_microblaze_0_axi_intc_0_stub.v
      E:/ECE385/lab6_2.xpr/lab6_2/lab6_2.runs/synth_1/.Xil/Vivado-11704-DESKTOP-02DFB66/realtime/mb_block_mdm_1_0_stub.v
      E:/ECE385/lab6_2.xpr/lab6_2/lab6_2.runs/synth_1/.Xil/Vivado-11704-DESKTOP-02DFB66/realtime/mb_block_clk_wiz_1_0_stub.v
      E:/ECE385/lab6_2.xpr/lab6_2/lab6_2.runs/synth_1/.Xil/Vivado-11704-DESKTOP-02DFB66/realtime/mb_block_rst_clk_wiz_1_100M_0_stub.v
      E:/ECE385/lab6_2.xpr/lab6_2/lab6_2.runs/synth_1/.Xil/Vivado-11704-DESKTOP-02DFB66/realtime/mb_block_axi_uartlite_0_0_stub.v
      E:/ECE385/lab6_2.xpr/lab6_2/lab6_2.runs/synth_1/.Xil/Vivado-11704-DESKTOP-02DFB66/realtime/mb_block_axi_gpio_0_1_stub.v
      E:/ECE385/lab6_2.xpr/lab6_2/lab6_2.runs/synth_1/.Xil/Vivado-11704-DESKTOP-02DFB66/realtime/mb_block_axi_gpio_3_0_stub.v
      E:/ECE385/lab6_2.xpr/lab6_2/lab6_2.runs/synth_1/.Xil/Vivado-11704-DESKTOP-02DFB66/realtime/mb_block_axi_gpio_4_0_stub.v
      E:/ECE385/lab6_2.xpr/lab6_2/lab6_2.runs/synth_1/.Xil/Vivado-11704-DESKTOP-02DFB66/realtime/mb_block_axi_timer_0_0_stub.v
      E:/ECE385/lab6_2.xpr/lab6_2/lab6_2.runs/synth_1/.Xil/Vivado-11704-DESKTOP-02DFB66/realtime/mb_block_axi_quad_spi_0_0_stub.v
      E:/ECE385/lab6_2.xpr/lab6_2/lab6_2.runs/synth_1/.Xil/Vivado-11704-DESKTOP-02DFB66/realtime/hdmi_tx_0_stub.v
      E:/ECE385/lab6_2.xpr/lab6_2/lab6_2.runs/synth_1/.Xil/Vivado-11704-DESKTOP-02DFB66/realtime/clk_wiz_0_stub.v
      e:/ECE385/lab6_2.xpr/lab6_2/lab6_2.gen/sources_1/bd/mb_block/synth/mb_block.v
    }
      rt::read_verilog -include {
    e:/ECE385/lab6_2.xpr/lab6_2/lab6_2.gen/sources_1/bd/mb_block/ipshared/ec67/hdl
    e:/ECE385/lab6_2.xpr/lab6_2/lab6_2.gen/sources_1/bd/mb_block/ipshared/7698
    e:/ECE385/lab6_2.xpr/lab6_2/lab6_2.gen/sources_1/ip/clk_wiz_0
    e:/ECE385/lab6_2.xpr/lab6_2/lab6_2.gen/sources_1/bd/mb_block/ip/mb_block_axi_quad_spi_0_0/netlist
  } {
      e:/ECE385/lab6_2.xpr/lab6_2/lab6_2.gen/sources_1/bd/mb_block/ipshared/4b67/hdl/xlconcat_v2_1_vl_rfs.v
      e:/ECE385/lab6_2.xpr/lab6_2/lab6_2.gen/sources_1/bd/mb_block/ip/mb_block_xlconcat_0_0/synth/mb_block_xlconcat_0_0.v
    }
      rt::read_vhdl -lib xpm E:/Vivado/2022.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList E:/ECE385/lab6_2.xpr/lab6_2/lab6_2.runs/synth_1/.Xil/Vivado-11704-DESKTOP-02DFB66/realtime/mb_usb_hdmi_top_synth.xdc
    rt::sdcChecksum
    set rt::top mb_usb_hdmi_top
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {E:/ECE385/lab6_2.xpr/lab6_2/lab6_2.cache/wt}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "E:/ECE385/lab6_2.xpr/lab6_2/lab6_2.runs/synth_1/.Xil/Vivado-11704-DESKTOP-02DFB66/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    rt::close_pss_mem_watcher
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    rt::set_parameter incrementalOnCache ""
    rt::set_parameter doIncremental false
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
